# Site settings
title: Aaroodd UR
description:
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaroodd
user_description: 
user_title: 
email: aaroodd@gmail.com
github_username:  aaroodd
#gplus_username:  
#twitter_username: 

# Google Analytics
google_analytics: UA-216277363-1


exclude: ['package.json', 'src' , 'node_modules']
